---

- hosts: all
<<<<<<< HEAD
  become:
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install apache2 package 
    apt:
      name: apache2
      state: latest

=======
  become: true
  tasks:
  
  - name: update repository
    apt:
      update_cache: yes
      
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
      
>>>>>>> d8c84d88e7fe01b802606adfab29d1a4c7babee0
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
<<<<<<< HEAD
=======
  
>>>>>>> d8c84d88e7fe01b802606adfab29d1a4c7babee0
