---

- hosts: all
<<<<<<< HEAD
  become:
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install apache2 package 
=======
  become: true
  tasks:
  
  - name: update repository
    apt:
      update_cache: yes
      
  - name: uninstall apache2 package
>>>>>>> d8c84d88e7fe01b802606adfab29d1a4c7babee0
    apt:
      name: apache2
      state: absent
